### PR TITLE
Add welcome page

### PR DESCRIPTION
**Pull request by Sporandum**
Hello,

I don't know if I do the things right, but I have created a new branch `add-home-page` and made some improvements in index.html as you wish.

I hope you enjoy it.

### CODE REVIEW

**Review by DamienCassou — COMMENTED** [review]
I like it, great work! Before I merge, would you please squash your 3 commits into 1? This can be done with an interactive rebase for example. Another solution is a soft reset. I can explain more if you need it.

**Comment by Sporandum** [comment]
Done 👍 .

Thanks for the advice.

**Review by DamienCassou — APPROVED** [review]
Great job!

**Comment by Sporandum** [comment]
Thanks a lot!

**Pull request merged**
